#!/usr/bin/env bash
# /etc/passwd using awk

awk -F: '{
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s'\''s place is protected by the passcode %s, more info about the user here: %s\n", \
           $1, $4, $6, $7, $3, $2, $5
}' /etc/passwd

