#!/usr/bin/env bash
# Show PID

for pid in /proc/[0-9]*
do
    name=$(basename "$(readlink -f "$pid/exe")" 2>/dev/null)

    if echo "$name" | grep -q "bash"; then
        echo "$(basename "$pid") $name"
    fi
done
